# Official node image
FROM node:22

# Sets working directory to /app inside container 
WORKDIR /app

# Copy dependencies from local directory to container's /app dir.
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all files from local directory to container's /app
COPY . /app

# Make application run on port 3000 
EXPOSE 3000

# Command to run the application
CMD ["npm", "start"]